version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8888:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3333/basics?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3333:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: shrikant
      MYSQL_PASSWORD: kale
      MYSQL_ROOT_PASSWORD: root
networks:
  springapimysql-net: