spring:
  application:
    name: SpringBootMySqlDocker
  datasource:
    username: shrikant
    password: kale
    initialization-mode: always
    url: jdbc:mysql://mysqldb:3333/basics?allowPublicKeyRetrieval=true
  sql:
    init:
      mode: 'always'
  jpa:
    hibernate:
      ddl-auto: update